name: Code Quality

on:
  pull_request:
    branches: [ 'main', 'dev' ]
    types:
      - opened
      - synchronize
  push:
    branches: [ 'dev' ]
  workflow_dispatch:
    if: github.actor != 'dependabot[bot]'

permissions:
  contents: read

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'


      - name: Setup Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/pip
          key: pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
            pre-commit-

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit
          pre-commit --version
        shell: bash

      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        name: Install pre-commit hooks
        run: pre-commit install
        shell: bash

      - name: Run pre-commit
        run: pre-commit run --all-files
        shell: bash
